// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LActionApprovedCancel() {
  return window['go']['program']['LProgram']['LActionApprovedCancel']();
}

export function LCatalogPresetSourceGet(arg1, arg2) {
  return window['go']['program']['LProgram']['LCatalogPresetSourceGet'](arg1, arg2);
}

export function LCatalogSourceGet(arg1, arg2) {
  return window['go']['program']['LProgram']['LCatalogSourceGet'](arg1, arg2);
}

export function LDirectoryResultOpen(arg1) {
  return window['go']['program']['LProgram']['LDirectoryResultOpen'](arg1);
}

export function LFileRecordOpen(arg1, arg2, arg3) {
  return window['go']['program']['LProgram']['LFileRecordOpen'](arg1, arg2, arg3);
}

export function LFolderLogOpen(arg1) {
  return window['go']['program']['LProgram']['LFolderLogOpen'](arg1);
}

export function LFolderRecordOpen(arg1, arg2) {
  return window['go']['program']['LProgram']['LFolderRecordOpen'](arg1, arg2);
}

export function LLinkExternalOpen(arg1) {
  return window['go']['program']['LProgram']['LLinkExternalOpen'](arg1);
}

export function LLocaleSet(arg1) {
  return window['go']['program']['LProgram']['LLocaleSet'](arg1);
}

export function LPlanFFmpegApprove(arg1, arg2) {
  return window['go']['program']['LProgram']['LPlanFFmpegApprove'](arg1, arg2);
}

export function LPlanFFmpegRequest(arg1) {
  return window['go']['program']['LProgram']['LPlanFFmpegRequest'](arg1);
}

export function LPlanToolchainApprove(arg1, arg2) {
  return window['go']['program']['LProgram']['LPlanToolchainApprove'](arg1, arg2);
}

export function LPlanToolchainRequest(arg1) {
  return window['go']['program']['LProgram']['LPlanToolchainRequest'](arg1);
}

export function LProfileToolchainList(arg1) {
  return window['go']['program']['LProgram']['LProfileToolchainList'](arg1);
}

export function LRecordLogGet(arg1, arg2) {
  return window['go']['program']['LProgram']['LRecordLogGet'](arg1, arg2);
}

export function LRecordLogList(arg1) {
  return window['go']['program']['LProgram']['LRecordLogList'](arg1);
}

export function LReportResultOpen(arg1) {
  return window['go']['program']['LProgram']['LReportResultOpen'](arg1);
}

export function LResultBuildGet(arg1) {
  return window['go']['program']['LProgram']['LResultBuildGet'](arg1);
}

export function LStateInitialGet() {
  return window['go']['program']['LProgram']['LStateInitialGet']();
}

export function LStateUiLoad() {
  return window['go']['program']['LProgram']['LStateUiLoad']();
}

export function LStateUiSave(arg1) {
  return window['go']['program']['LProgram']['LStateUiSave'](arg1);
}

export function LStatusToolchainGet(arg1, arg2) {
  return window['go']['program']['LProgram']['LStatusToolchainGet'](arg1, arg2);
}

export function LToolchainEnvironmentClear(arg1) {
  return window['go']['program']['LProgram']['LToolchainEnvironmentClear'](arg1);
}

export function LToolchainInstallVerify(arg1, arg2) {
  return window['go']['program']['LProgram']['LToolchainInstallVerify'](arg1, arg2);
}

export function LVerificationBuildRun(arg1) {
  return window['go']['program']['LProgram']['LVerificationBuildRun'](arg1);
}

export function LWorkspaceSelect() {
  return window['go']['program']['LProgram']['LWorkspaceSelect']();
}
