// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {audit} from '../models';
import {planning} from '../models';
import {context} from '../models';
import {consent} from '../models';
import {program} from '../models';
import {workspace} from '../models';

export function LActionApprovedCancel():Promise<boolean>;

export function LActionApprovedFinish(arg1:string):Promise<void>;

export function LActionApprovedStart():Promise<string>;

export function LActionFailureEmit(arg1:audit.LAuditWriter,arg2:planning.LPlanFfmpeg,arg3:string,arg4:string,arg5:Error):Promise<boolean>;

export function LApprovalConfirmationResolve(arg1:string,arg2:boolean):Promise<void>;

export function LAuditProgressCreate(arg1:audit.LAuditWriter,arg2:string,arg3:string):Promise<any>;

export function LCatalogSourceGet(arg1:string,arg2:string):Promise<Array<planning.LLibraryChoice>>;

export function LDependencyInstall(arg1:context.Context,arg2:planning.LPlanFfmpeg,arg3:planning.LLibraryPreparation,arg4:consent.LConsentPacman,arg5:audit.LAuditWriter,arg6:any):Promise<void>;

export function LDirectoryResultOpen(arg1:string,arg2:string):Promise<void>;

export function LErrorLocalizedEmit(arg1:string,arg2:string,arg3:Error):Promise<void>;

export function LFfmpegApproveSync(arg1:string,arg2:consent.LRequestApproval):Promise<program.LResultAction>;

export function LFfmpegApproveValidate(arg1:string,arg2:consent.LRequestApproval):Promise<planning.LPlanFfmpeg>;

export function LFfmpegCompilationLaunch(arg1:planning.LPlanFfmpeg,arg2:consent.LRequestApproval,arg3:boolean):Promise<program.LResultAction>;

export function LFfmpegCompile(arg1:context.Context,arg2:string,arg3:planning.LPlanFfmpeg,arg4:consent.LConsentFfmpeg,arg5:consent.LArchiveConsentState,arg6:consent.LConsentPacman,arg7:consent.LConsentCommand):Promise<void>;

export function LFfmpegConfigureRun(arg1:context.Context,arg2:planning.LPlanFfmpeg,arg3:string,arg4:consent.LConsentCommand,arg5:audit.LAuditWriter,arg6:any):Promise<void>;

export function LFfmpegFailureClean(arg1:planning.LPlanFfmpeg,arg2:workspace.LWorkspaceLayout,arg3:string):Promise<void>;

export function LFfmpegMakeRun(arg1:context.Context,arg2:planning.LPlanFfmpeg,arg3:string,arg4:consent.LConsentCommand,arg5:audit.LAuditWriter,arg6:any):Promise<void>;

export function LFfmpegReviewConsume(arg1:string):Promise<void>;

export function LFfmpegReviewValidate(arg1:string,arg2:consent.LRequestApproval):Promise<program.LReviewFfmpegStored>;

export function LFileRecordOpen(arg1:string,arg2:string,arg3:string):Promise<void>;

export function LFolderLogOpen(arg1:string):Promise<void>;

export function LFolderRecordOpen(arg1:string,arg2:string):Promise<void>;

export function LLibraryNonnativePrepare(arg1:context.Context,arg2:planning.LPlanFfmpeg,arg3:consent.LConsentFfmpeg,arg4:consent.LArchiveConsentState,arg5:consent.LConsentPacman,arg6:consent.LConsentCommand,arg7:audit.LAuditWriter,arg8:any):Promise<void>;

export function LLibraryPackageInstall(arg1:context.Context,arg2:planning.LPlanFfmpeg,arg3:consent.LConsentPacman,arg4:audit.LAuditWriter,arg5:any):Promise<void>;

export function LLibrarySinglePrepare(arg1:context.Context,arg2:planning.LPlanFfmpeg,arg3:planning.LLibraryPreparation,arg4:consent.LConsentFfmpeg,arg5:consent.LArchiveConsentState,arg6:consent.LConsentPacman,arg7:consent.LConsentCommand,arg8:audit.LAuditWriter,arg9:any):Promise<void>;

export function LLibraryVersionValidate(arg1:planning.LPlanFfmpeg,arg2:string,arg3:any):Promise<void>;

export function LLinkExternalOpen(arg1:string):Promise<void>;

export function LLocaleSet(arg1:string):Promise<void>;

export function LLogConfigurationSave(arg1:string,arg2:string):Promise<void>;

export function LLogEmit(arg1:string,arg2:string):Promise<void>;

export function LLogRecordList(arg1:string):Promise<Array<program.LRecordLog>>;

export function LNativeConsentAsk(arg1:string,arg2:string):Promise<boolean>;

export function LPacmanPackageInstall(arg1:context.Context,arg2:planning.LPlanToolchain,arg3:consent.LConsentPacman,arg4:audit.LAuditWriter,arg5:any):Promise<void>;

export function LPlanFfmpegApprove(arg1:string,arg2:consent.LRequestApproval):Promise<program.LResultAction>;

export function LPlanFfmpegRequest(arg1:planning.LSettingsFfmpeg):Promise<planning.LReviewFfmpeg>;

export function LPlanToolchainApprove(arg1:string,arg2:consent.LRequestApproval):Promise<program.LResultAction>;

export function LPlanToolchainRequest(arg1:planning.LSettingsToolchain):Promise<planning.LReviewToolchain>;

export function LPreparationRemove(arg1:string,arg2:string):Promise<void>;

export function LPresetSourceGet(arg1:string,arg2:string):Promise<Array<planning.LPresetLibraryChoice>>;

export function LRecordLogGet(arg1:string,arg2:string):Promise<program.LRecordLog>;

export function LReportResultOpen(arg1:string,arg2:string):Promise<void>;

export function LResultBuildGet(arg1:string):Promise<program.LResultState>;

export function LStateInitialGet():Promise<program.LStateInitial>;

export function LStateUiLoad():Promise<string>;

export function LStateUiSave(arg1:string):Promise<void>;

export function LStatusEmit(arg1:string):Promise<void>;

export function LStatusFailureEmit(arg1:string,arg2:Error):Promise<void>;

export function LStatusToolchainGet(arg1:string,arg2:string):Promise<program.LStatusToolchain>;

export function LToolchainApproveSync(arg1:string,arg2:consent.LRequestApproval):Promise<program.LResultAction>;

export function LToolchainApproveValidate(arg1:string,arg2:consent.LRequestApproval):Promise<planning.LPlanToolchain>;

export function LToolchainEnvironmentClear(arg1:string):Promise<void>;

export function LToolchainFailureClean(arg1:planning.LPlanToolchain,arg2:workspace.LWorkspaceLayout):Promise<void>;

export function LToolchainFreshPrepare(arg1:string,arg2:string,arg3:any):Promise<void>;

export function LToolchainInstallVerify(arg1:string,arg2:string):Promise<program.LVerificationToolchain>;

export function LToolchainPrepare(arg1:context.Context,arg2:string,arg3:planning.LPlanToolchain,arg4:consent.LConsentMsys,arg5:consent.LArchiveConsentState,arg6:consent.LConsentPacman):Promise<void>;

export function LToolchainPrepareLaunch(arg1:planning.LPlanToolchain,arg2:consent.LRequestApproval,arg3:boolean):Promise<program.LResultAction>;

export function LToolchainProfileList(arg1:string):Promise<Array<program.LStatusToolchain>>;

export function LToolchainReviewConsume(arg1:string):Promise<void>;

export function LToolchainReviewValidate(arg1:string,arg2:consent.LRequestApproval):Promise<program.LReviewToolchainStored>;

export function LVerificationBuildRun(arg1:string):Promise<program.LVerificationState>;

export function LWindowGeometryRestore():Promise<void>;

export function LWindowGeometrySave(arg1:context.Context):Promise<void>;

export function LWorkspaceSelect():Promise<string>;

export function LWorkspaceTargetsClean(arg1:string,arg2:Array<string>):Promise<void>;
