// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LActionApprovedCancel() {
  return window['go']['program']['LProgram']['LActionApprovedCancel']();
}

export function LActionApprovedFinish(arg1) {
  return window['go']['program']['LProgram']['LActionApprovedFinish'](arg1);
}

export function LActionApprovedStart() {
  return window['go']['program']['LProgram']['LActionApprovedStart']();
}

export function LActionFailureEmit(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['program']['LProgram']['LActionFailureEmit'](arg1, arg2, arg3, arg4, arg5);
}

export function LApprovalConfirmationResolve(arg1, arg2) {
  return window['go']['program']['LProgram']['LApprovalConfirmationResolve'](arg1, arg2);
}

export function LAuditProgressCreate(arg1, arg2, arg3) {
  return window['go']['program']['LProgram']['LAuditProgressCreate'](arg1, arg2, arg3);
}

export function LCatalogSourceGet(arg1, arg2) {
  return window['go']['program']['LProgram']['LCatalogSourceGet'](arg1, arg2);
}

export function LDependencyInstall(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['program']['LProgram']['LDependencyInstall'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function LDirectoryResultOpen(arg1, arg2) {
  return window['go']['program']['LProgram']['LDirectoryResultOpen'](arg1, arg2);
}

export function LErrorLocalizedEmit(arg1, arg2, arg3) {
  return window['go']['program']['LProgram']['LErrorLocalizedEmit'](arg1, arg2, arg3);
}

export function LFfmpegApproveSync(arg1, arg2) {
  return window['go']['program']['LProgram']['LFfmpegApproveSync'](arg1, arg2);
}

export function LFfmpegApproveValidate(arg1, arg2) {
  return window['go']['program']['LProgram']['LFfmpegApproveValidate'](arg1, arg2);
}

export function LFfmpegCompilationLaunch(arg1, arg2, arg3) {
  return window['go']['program']['LProgram']['LFfmpegCompilationLaunch'](arg1, arg2, arg3);
}

export function LFfmpegCompile(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['program']['LProgram']['LFfmpegCompile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function LFfmpegConfigureRun(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['program']['LProgram']['LFfmpegConfigureRun'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function LFfmpegFailureClean(arg1, arg2, arg3) {
  return window['go']['program']['LProgram']['LFfmpegFailureClean'](arg1, arg2, arg3);
}

export function LFfmpegMakeRun(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['program']['LProgram']['LFfmpegMakeRun'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function LFfmpegReviewConsume(arg1) {
  return window['go']['program']['LProgram']['LFfmpegReviewConsume'](arg1);
}

export function LFfmpegReviewValidate(arg1, arg2) {
  return window['go']['program']['LProgram']['LFfmpegReviewValidate'](arg1, arg2);
}

export function LFileRecordOpen(arg1, arg2, arg3) {
  return window['go']['program']['LProgram']['LFileRecordOpen'](arg1, arg2, arg3);
}

export function LFolderLogOpen(arg1) {
  return window['go']['program']['LProgram']['LFolderLogOpen'](arg1);
}

export function LFolderRecordOpen(arg1, arg2) {
  return window['go']['program']['LProgram']['LFolderRecordOpen'](arg1, arg2);
}

export function LLibraryNonnativePrepare(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['program']['LProgram']['LLibraryNonnativePrepare'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function LLibraryPackageInstall(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['program']['LProgram']['LLibraryPackageInstall'](arg1, arg2, arg3, arg4, arg5);
}

export function LLibrarySinglePrepare(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['program']['LProgram']['LLibrarySinglePrepare'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function LLibraryVersionValidate(arg1, arg2, arg3) {
  return window['go']['program']['LProgram']['LLibraryVersionValidate'](arg1, arg2, arg3);
}

export function LLinkExternalOpen(arg1) {
  return window['go']['program']['LProgram']['LLinkExternalOpen'](arg1);
}

export function LLocaleSet(arg1) {
  return window['go']['program']['LProgram']['LLocaleSet'](arg1);
}

export function LLogConfigurationSave(arg1, arg2) {
  return window['go']['program']['LProgram']['LLogConfigurationSave'](arg1, arg2);
}

export function LLogEmit(arg1, arg2) {
  return window['go']['program']['LProgram']['LLogEmit'](arg1, arg2);
}

export function LLogRecordList(arg1) {
  return window['go']['program']['LProgram']['LLogRecordList'](arg1);
}

export function LNativeConsentAsk(arg1, arg2) {
  return window['go']['program']['LProgram']['LNativeConsentAsk'](arg1, arg2);
}

export function LPacmanPackageInstall(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['program']['LProgram']['LPacmanPackageInstall'](arg1, arg2, arg3, arg4, arg5);
}

export function LPlanFfmpegApprove(arg1, arg2) {
  return window['go']['program']['LProgram']['LPlanFfmpegApprove'](arg1, arg2);
}

export function LPlanFfmpegRequest(arg1) {
  return window['go']['program']['LProgram']['LPlanFfmpegRequest'](arg1);
}

export function LPlanToolchainApprove(arg1, arg2) {
  return window['go']['program']['LProgram']['LPlanToolchainApprove'](arg1, arg2);
}

export function LPlanToolchainRequest(arg1) {
  return window['go']['program']['LProgram']['LPlanToolchainRequest'](arg1);
}

export function LPreparationRemove(arg1, arg2) {
  return window['go']['program']['LProgram']['LPreparationRemove'](arg1, arg2);
}

export function LPresetSourceGet(arg1, arg2) {
  return window['go']['program']['LProgram']['LPresetSourceGet'](arg1, arg2);
}

export function LRecordLogGet(arg1, arg2) {
  return window['go']['program']['LProgram']['LRecordLogGet'](arg1, arg2);
}

export function LReportResultOpen(arg1, arg2) {
  return window['go']['program']['LProgram']['LReportResultOpen'](arg1, arg2);
}

export function LResultBuildGet(arg1) {
  return window['go']['program']['LProgram']['LResultBuildGet'](arg1);
}

export function LStateInitialGet() {
  return window['go']['program']['LProgram']['LStateInitialGet']();
}

export function LStateUiLoad() {
  return window['go']['program']['LProgram']['LStateUiLoad']();
}

export function LStateUiSave(arg1) {
  return window['go']['program']['LProgram']['LStateUiSave'](arg1);
}

export function LStatusEmit(arg1) {
  return window['go']['program']['LProgram']['LStatusEmit'](arg1);
}

export function LStatusFailureEmit(arg1, arg2) {
  return window['go']['program']['LProgram']['LStatusFailureEmit'](arg1, arg2);
}

export function LStatusToolchainGet(arg1, arg2) {
  return window['go']['program']['LProgram']['LStatusToolchainGet'](arg1, arg2);
}

export function LToolchainApproveSync(arg1, arg2) {
  return window['go']['program']['LProgram']['LToolchainApproveSync'](arg1, arg2);
}

export function LToolchainApproveValidate(arg1, arg2) {
  return window['go']['program']['LProgram']['LToolchainApproveValidate'](arg1, arg2);
}

export function LToolchainEnvironmentClear(arg1) {
  return window['go']['program']['LProgram']['LToolchainEnvironmentClear'](arg1);
}

export function LToolchainFailureClean(arg1, arg2) {
  return window['go']['program']['LProgram']['LToolchainFailureClean'](arg1, arg2);
}

export function LToolchainFreshPrepare(arg1, arg2, arg3) {
  return window['go']['program']['LProgram']['LToolchainFreshPrepare'](arg1, arg2, arg3);
}

export function LToolchainInstallVerify(arg1, arg2) {
  return window['go']['program']['LProgram']['LToolchainInstallVerify'](arg1, arg2);
}

export function LToolchainPrepare(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['program']['LProgram']['LToolchainPrepare'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function LToolchainPrepareLaunch(arg1, arg2, arg3) {
  return window['go']['program']['LProgram']['LToolchainPrepareLaunch'](arg1, arg2, arg3);
}

export function LToolchainProfileList(arg1) {
  return window['go']['program']['LProgram']['LToolchainProfileList'](arg1);
}

export function LToolchainReviewConsume(arg1) {
  return window['go']['program']['LProgram']['LToolchainReviewConsume'](arg1);
}

export function LToolchainReviewValidate(arg1, arg2) {
  return window['go']['program']['LProgram']['LToolchainReviewValidate'](arg1, arg2);
}

export function LVerificationBuildRun(arg1) {
  return window['go']['program']['LProgram']['LVerificationBuildRun'](arg1);
}

export function LWindowGeometryRestore() {
  return window['go']['program']['LProgram']['LWindowGeometryRestore']();
}

export function LWindowGeometrySave(arg1) {
  return window['go']['program']['LProgram']['LWindowGeometrySave'](arg1);
}

export function LWorkspaceSelect() {
  return window['go']['program']['LProgram']['LWorkspaceSelect']();
}

export function LWorkspaceTargetsClean(arg1, arg2) {
  return window['go']['program']['LProgram']['LWorkspaceTargetsClean'](arg1, arg2);
}
