// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {planning} from '../models';
import {consent} from '../models';
import {program} from '../models';

export function LActionApprovedCancel():Promise<boolean>;

export function LCatalogPresetSourceGet(arg1:string,arg2:string):Promise<Array<planning.LPresetLibraryChoice>>;

export function LCatalogSourceGet(arg1:string,arg2:string):Promise<Array<planning.LLibraryChoice>>;

export function LDirectoryResultOpen(arg1:string):Promise<void>;

export function LFileRecordOpen(arg1:string,arg2:string,arg3:string):Promise<void>;

export function LFolderLogOpen(arg1:string):Promise<void>;

export function LFolderRecordOpen(arg1:string,arg2:string):Promise<void>;

export function LLinkExternalOpen(arg1:string):Promise<void>;

export function LLocaleSet(arg1:string):Promise<void>;

export function LPlanFFmpegApprove(arg1:string,arg2:consent.LRequestApproval):Promise<program.LResultAction>;

export function LPlanFFmpegRequest(arg1:planning.LSettingsFFmpeg):Promise<planning.LReviewFFmpeg>;

export function LPlanToolchainApprove(arg1:string,arg2:consent.LRequestApproval):Promise<program.LResultAction>;

export function LPlanToolchainRequest(arg1:planning.LSettingsBuild):Promise<planning.LReviewToolchain>;

export function LProfileToolchainList(arg1:string):Promise<Array<program.LStatusToolchain>>;

export function LRecordLogGet(arg1:string,arg2:string):Promise<program.LRecordLog>;

export function LRecordLogList(arg1:string):Promise<Array<program.LRecordLog>>;

export function LReportResultOpen(arg1:string):Promise<void>;

export function LResultBuildGet(arg1:string):Promise<program.LResultBuild>;

export function LStateInitialGet():Promise<program.LStateInitial>;

export function LStateUiLoad():Promise<string>;

export function LStateUiSave(arg1:string):Promise<void>;

export function LStatusToolchainGet(arg1:string,arg2:string):Promise<program.LStatusToolchain>;

export function LToolchainEnvironmentClear(arg1:string):Promise<void>;

export function LToolchainInstallVerify(arg1:string,arg2:string):Promise<program.LVerificationToolchain>;

export function LVerificationBuildRun(arg1:string):Promise<program.LVerificationBuild>;

export function LWorkspaceSelect():Promise<string>;
