// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {consent} from '../models';
import {app} from '../models';
import {planning} from '../models';

export function ApproveFfmpegBuildPlan(arg1:string,arg2:consent.ApprovalRequest):Promise<app.ApprovedActionResult>;

export function ApproveToolchainPreparationPlan(arg1:string,arg2:consent.ApprovalRequest):Promise<app.ApprovedActionResult>;

export function CancelApprovedAction():Promise<boolean>;

export function GetBuildResult(arg1:string):Promise<app.BuildResult>;

export function GetInitialApplicationState():Promise<app.InitialApplicationState>;

export function LoadUiState():Promise<string>;

export function OpenExternalUrl(arg1:string):Promise<void>;

export function OpenResultFolder(arg1:string):Promise<void>;

export function RequestFfmpegBuildPlan(arg1:planning.FfmpegBuildSettings):Promise<planning.FfmpegBuildPlanReview>;

export function RequestToolchainPreparationPlan(arg1:planning.BuildToolSettings):Promise<planning.ToolchainPreparationPlanReview>;

export function SaveUiState(arg1:string):Promise<void>;

export function SelectWorkspace():Promise<string>;
