// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveFfmpegBuildPlan(arg1, arg2) {
  return window['go']['app']['App']['ApproveFfmpegBuildPlan'](arg1, arg2);
}

export function ApproveToolchainPreparationPlan(arg1, arg2) {
  return window['go']['app']['App']['ApproveToolchainPreparationPlan'](arg1, arg2);
}

export function CancelApprovedAction() {
  return window['go']['app']['App']['CancelApprovedAction']();
}

export function ClearBuildEnvironments(arg1) {
  return window['go']['app']['App']['ClearBuildEnvironments'](arg1);
}

export function GetBuildResult(arg1) {
  return window['go']['app']['App']['GetBuildResult'](arg1);
}

export function GetInitialApplicationState() {
  return window['go']['app']['App']['GetInitialApplicationState']();
}

export function GetInstalledToolchainProfiles(arg1) {
  return window['go']['app']['App']['GetInstalledToolchainProfiles'](arg1);
}

export function GetLibraryCatalogForFfmpegSource(arg1, arg2) {
  return window['go']['app']['App']['GetLibraryCatalogForFfmpegSource'](arg1, arg2);
}

export function GetLocalLogRecord(arg1, arg2) {
  return window['go']['app']['App']['GetLocalLogRecord'](arg1, arg2);
}

export function GetToolchainStatus(arg1, arg2) {
  return window['go']['app']['App']['GetToolchainStatus'](arg1, arg2);
}

export function ListLocalLogRecords(arg1) {
  return window['go']['app']['App']['ListLocalLogRecords'](arg1);
}

export function LoadUiState() {
  return window['go']['app']['App']['LoadUiState']();
}

export function OpenExternalUrl(arg1) {
  return window['go']['app']['App']['OpenExternalUrl'](arg1);
}

export function OpenLocalLogRecordFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['OpenLocalLogRecordFile'](arg1, arg2, arg3);
}

export function OpenLocalLogRecordFolder(arg1, arg2) {
  return window['go']['app']['App']['OpenLocalLogRecordFolder'](arg1, arg2);
}

export function OpenLocalLogsFolder(arg1) {
  return window['go']['app']['App']['OpenLocalLogsFolder'](arg1);
}

export function OpenResultFolder(arg1) {
  return window['go']['app']['App']['OpenResultFolder'](arg1);
}

export function OpenResultReport(arg1) {
  return window['go']['app']['App']['OpenResultReport'](arg1);
}

export function RequestFfmpegBuildPlan(arg1) {
  return window['go']['app']['App']['RequestFfmpegBuildPlan'](arg1);
}

export function RequestToolchainPreparationPlan(arg1) {
  return window['go']['app']['App']['RequestToolchainPreparationPlan'](arg1);
}

export function SaveUiState(arg1) {
  return window['go']['app']['App']['SaveUiState'](arg1);
}

export function SelectWorkspace(arg1) {
  return window['go']['app']['App']['SelectWorkspace'](arg1);
}

export function SetLocale(arg1) {
  return window['go']['app']['App']['SetLocale'](arg1);
}

export function VerifyBuildResult(arg1) {
  return window['go']['app']['App']['VerifyBuildResult'](arg1);
}

export function VerifyToolchainInstallation(arg1, arg2) {
  return window['go']['app']['App']['VerifyToolchainInstallation'](arg1, arg2);
}
