// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {consent} from '../models';
import {app} from '../models';
import {planning} from '../models';

export function ApproveFfmpegBuildPlan(arg1:string,arg2:consent.ApprovalRequest):Promise<app.ApprovedActionResult>;

export function ApproveToolchainPreparationPlan(arg1:string,arg2:consent.ApprovalRequest):Promise<app.ApprovedActionResult>;

export function CancelApprovedAction():Promise<boolean>;

export function ClearBuildEnvironments(arg1:string):Promise<void>;

export function GetBuildResult(arg1:string):Promise<app.BuildResult>;

export function GetInitialApplicationState():Promise<app.InitialApplicationState>;

export function GetInstalledToolchainProfiles(arg1:string):Promise<Array<app.ToolchainStatus>>;

export function GetLibraryCatalogForFfmpegSource(arg1:string,arg2:string):Promise<Array<planning.LibraryChoice>>;

export function GetLocalLogRecord(arg1:string,arg2:string):Promise<app.LocalLogRecord>;

export function GetToolchainStatus(arg1:string,arg2:string):Promise<app.ToolchainStatus>;

export function ListLocalLogRecords(arg1:string):Promise<Array<app.LocalLogRecord>>;

export function LoadUiState():Promise<string>;

export function OpenExternalUrl(arg1:string):Promise<void>;

export function OpenLocalLogRecordFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenLocalLogRecordFolder(arg1:string,arg2:string):Promise<void>;

export function OpenLocalLogsFolder(arg1:string):Promise<void>;

export function OpenResultFolder(arg1:string):Promise<void>;

export function OpenResultReport(arg1:string):Promise<void>;

export function RequestFfmpegBuildPlan(arg1:planning.FfmpegBuildSettings):Promise<planning.FfmpegBuildPlanReview>;

export function RequestToolchainPreparationPlan(arg1:planning.BuildConfigSettings):Promise<planning.ToolchainPreparationPlanReview>;

export function SaveUiState(arg1:string):Promise<void>;

export function SelectWorkspace(arg1:string):Promise<string>;

export function SetLocale(arg1:string):Promise<void>;

export function VerifyBuildResult(arg1:string):Promise<app.BuildVerification>;

export function VerifyToolchainInstallation(arg1:string,arg2:string):Promise<app.ToolchainVerification>;
