// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveFfmpegBuildPlan(arg1, arg2) {
  return window['go']['main']['App']['ApproveFfmpegBuildPlan'](arg1, arg2);
}

export function ApproveToolchainPreparationPlan(arg1, arg2) {
  return window['go']['main']['App']['ApproveToolchainPreparationPlan'](arg1, arg2);
}

export function CancelApprovedAction() {
  return window['go']['main']['App']['CancelApprovedAction']();
}

export function GetBuildResult(arg1) {
  return window['go']['main']['App']['GetBuildResult'](arg1);
}

export function GetInitialApplicationState() {
  return window['go']['main']['App']['GetInitialApplicationState']();
}

export function OpenExternalUrl(arg1) {
  return window['go']['main']['App']['OpenExternalUrl'](arg1);
}

export function OpenResultFolder(arg1) {
  return window['go']['main']['App']['OpenResultFolder'](arg1);
}

export function RequestFfmpegBuildPlan(arg1) {
  return window['go']['main']['App']['RequestFfmpegBuildPlan'](arg1);
}

export function RequestToolchainPreparationPlan(arg1) {
  return window['go']['main']['App']['RequestToolchainPreparationPlan'](arg1);
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}
